readme-update
PiotrRynio/CodersCamp2021.Project.JavaScript pull request #94
Opened 2021-12-20 13:01 UTC by RadekDulisz

2021-12-20 14:20 UTC, PiotrRynio requested changes
Chwilowo blokuję, ale sprawdzę po pracy i dam znać. :)

Przepraszam ;)

2021-12-20 19:42 UTC, PiotrRynio approved these changes
Super zrobione. Dodałem małego commita z drobnymi zmianami, głównie kosmetycznymi.

Proszę, uzupełnij jeszcze, to co dodałem w CR.
Czyli tam, gdzie postawione są XXX.

Daję już Approve :)

2021-12-20 19:42 UTC, PiotrRynio commented on README.md
> +
Uzupełnij tutaj

2021-12-20 19:42 UTC, PiotrRynio commented on README.md
> +- Repo url: [LINK](XXX)
Tutaj

2021-12-20 19:42 UTC, PiotrRynio commented on README.md
> +This app has been created by a group of 6 people for a free coding program called CodersCamp.
```suggestion
This app has been created by a group of 6 people during CodersCamp course.
```

2021-12-21 07:28 UTC, PSwiecicki approved these changes
Ogólnie wow. Daje approve.

2021-12-21 09:11 UTC, merged